project:
  type: website
  output-dir: docs

website:
  title: "Ian's Webpage"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "Datastory (placeholder)"
      - href: documentation.qmd
        text: "Documentation (placeholder)"
      - href: week11challenge.qmd
        text: "wk 11 (to be deleted)"

        

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

