project:
  type: website
  output-dir: docs

website:
  title: "NM2207 Project: Ian's Website"
  navbar:
    left:
      - href: datastory.qmd
        text: "Datastory"

      - href: age.qmd
        text: "Age vs Singlehood"
      - href: index.qmd
        text: "About Me"
        

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

