project:
  type: website
  output-dir: docs

website:
  title: "NM2207 Project: Ian's Webpage"
  navbar:
    left:
      - href: datastory.qmd
        text: "Datastory"
      - href: documentation.qmd
        text: "Documentation (placeholder)"
      - href: spare.qmd
        text: "spare"
      - href: aboutme.qmd
        text: "About Me"
        

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

